# Generated by Django 2.2.1 on 2020-01-30 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('procedure', models.IntegerField()),
                ('this_week_proceed', models.IntegerField()),
                ('last_study', models.DateTimeField()),
                ('Time', models.IntegerField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='procedure.User')),
            ],
        ),
        migrations.CreateModel(
            name='refPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference', models.TextField()),
                ('Comment', models.TextField()),
                ('intro_image', models.ImageField(upload_to='')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.subject')),
            ],
        ),
    ]
