# Generated by Django 2.2.1 on 2020-02-17 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.IntegerField()),
                ('is_repeat_event', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='timeAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalWeeklyAmount', models.IntegerField()),
                ('totalMonthlyAmount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('procedure', models.IntegerField(default=0)),
                ('this_week_proceed', models.IntegerField(null=True)),
                ('last_study', models.DateTimeField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('category', models.IntegerField(default=0)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(default='', max_length=200)),
                ('reference', models.TextField()),
                ('description', models.TextField()),
                ('intro_image', models.ImageField(null=True, upload_to='')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_obj', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='procedure.Subject')),
            ],
        ),
    ]
