# Generated by Django 2.2.1 on 2020-01-30 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0002_auto_20200130_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refpost',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='refpost',
            old_name='Reference',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='Time',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='refpost',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.Subject'),
        ),
    ]
