# Generated by Django 2.2.1 on 2020-01-30 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0004_auto_20200130_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='refpost',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.Subject'),
        ),
    ]
