# Generated by Django 2.2.1 on 2020-01-30 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0006_auto_20200130_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalWeeklyAmount', models.IntegerField()),
                ('totalMonthlyAmount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='refpost',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.Subject'),
        ),
    ]
