# Generated by Django 2.2.1 on 2020-02-02 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procedure', '0012_auto_20200202_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='refpost',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refpost',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='last_study',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='this_week_proceed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
