# Generated by Django 2.2.1 on 2020-02-13 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procedure', '0015_auto_20200204_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='post_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.Subject'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(default='소개하는 글이 없습니다.')),
                ('detail', models.TextField(default='자세한 정보 글이 없습니다.')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=40)),
                ('statue', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=10)),
                ('postcode', models.CharField(max_length=6)),
                ('countProject', models.IntegerField(blank=True, default=0, null=True)),
                ('countPortfolio', models.IntegerField(blank=True, default=0, null=True)),
                ('countComment', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
