# Generated by Django 2.2.1 on 2020-02-14 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0020_auto_20200214_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='post_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.Subject'),
        ),
    ]
